### ISSUE TITLE
Write alt texts for all images

### ISSUE THREAD

**Issue by Frigyes06** [HackLab-Santa-Rosa/website#2]
Fill the alt attribute in every image to improve accessibility

**Comment by khushpreetsinghb** [comment]
I want to work on open-source projects. I can do this.

**Comment by Frigyes06** [comment]
@khushpreetsinghb of course! When you're done, open a pull request referencing this issue, and we'll check it out!

**Comment by Frigyes06** [comment]
closed by #9
